### ISSUE TITLE
About the result of test.py

### ISSUE THREAD

**Issue by zhanghuishun** [abduallahmohamed/Social-STGCNN#12]
Hi! Amazing work! 
But when I run test.py with given checkpoints, the results of ADE and FDE seem much lower than those in the paper. So could you please explain that? Is there anything  wrong with the steps? Thanks.

![image](https://user-images.githubusercontent.com/24810089/77127452-7a1be880-6a87-11ea-962b-9eb7384a8f12.png)

**Comment by abduallahmohamed** [comment]
Hi, 

I just rand the code: 
here's my log; 
can you make sure the you copied the repo correctly with the model weights? 
the number of samples is 20 ? 

![image](https://user-images.githubusercontent.com/22107547/77143457-55a51980-6a51-11ea-93ee-462bd0f19a0e.png)

You can notice a difference between my log and yours, it seems that the models checkpoints didn't load on your side correctly;

**Comment by zhanghuishun** [comment]
@abduallahmohamed Thanks you for reply!
I still have a question about the kernel size of st_gcn in model.py . I saw that you set graph convolving kernel  size = 8 which is observe seq length. I dont understand that.
Another question is that I would like to know if you have tried attention mechanism. Because I read the ST-GCN paper you reference, they put a attention in their network. Thanks again!

**Comment by abduallahmohamed** [comment]
For obs len = 8, we needed a features from each pedestrians trajectory that is able to match the adjacency matrix A.  take a look into this einsum: https://github.com/abduallahmohamed/Social-STGCNN/blob/ebd57aaf34d84763825d05cf9d4eff738d8c96bb/model.py#L74 
Say for example we have 2 pedestrains observed over 8 time steps, the A will have dime of (8,2,2), the vertices have dim of (2,8,2)  in order to have the einsum that represents the ST-GCNN to work we needed a graph kernel of 8. 

I tested the attention mechanism and it wasn't promising on my side, but I could say it was a naiive test and out of the scope for this work.

**Comment by zhanghuishun** [comment]
Thanks a lot!
