### ISSUE TITLE
Vertices attribute is relative coordinates in the code

### ISSUE THREAD

**Issue by srikanthmalla** [abduallahmohamed/Social-STGCNN#15]
Hi @abduallahmohamed ,
I want to clarify one thing from the paper and code:

In paper page 3, sec 4.1 paragraph 2 it is mentioned that " the observed location (xit, yit) is the attribute of vit)"

In the code utils.py (seq_to_graph) you used step_rel[h], which is (xit-xi(t-1), yit-yi(t-1)).
https://github.com/abduallahmohamed/Social-STGCNN/blob/master/utils.py#L42

Could you please clarify if you have mentioned it in the paper.

Thanks,
Srikanth

**Comment by abduallahmohamed** [comment]
Hi, 

As I stated before in earlier issue; the locations of pedestrians are in meters and there’s a different frames across datasets. So, we use the deltas as a method of normalization and to have a reasonable numbers in magnitudes. This is being used by social gan, lstm .. etc. So this is no mote than a transformation for the features. 
It wasn’t necessary to mention that level of implementation details in the paper. 

Thanks

**Comment by abduallahmohamed** [comment]
I also wanted to add that this a change of basis, feel free to ask more if this sames unclear.

**Comment by abduallahmohamed** [comment]
I will reopen this issue as it appears the usage of deltas moves us to velocity domain. The normalization in the dataset is being used across multiple works but apparently no one thought about the physical meaning of it. 
And also using 1/L2(of deltas) yields better results than 1/L2(of abs distances), both results still exceeds SOTA but a better understanding in necessary.

**Comment by stuarteiffert** [comment]
Hi @abduallahmohamed ,

I've tried implementing the use of abs distances rather than deltas  but have not been able to get good results.

I changed both V and A to use normalised absolute positions (step_) when creating the graph:
where V[s,h,:] = step_[h]
and A[s,h,k] = anorm(step_[h],step_[k])

Positions were normed wrt mean and stdev of each dataset (eg students003_train, crowds_zara02_train) and I left the deltas (seq_rel) unchanged (I don't think these were used anyway).  

Additionally, I have tried creating the graph as you suggested where A is 1/L2(abs distances), and also where A is just L2(abs distances), as this made more intuitive sense to me when using absolute distances between nodes, but have not seen good results with either approach.
Loss converged in training, but didnt decrease by much. The error was also very poor (>2m ADE on eth), where each dimension was rescaled to meters using the stdevs of test dataset

Have you managed to train with positional  input to both V and A, or compared the use of delta for V and position for A?

**Comment by abduallahmohamed** [comment]
@stuarteiffert 
If you only changed A to use the abs distance and leave V as it's you will end up with ADE/FDE =  0.49/0.85. It's not applicable to use abs distance for V due to different start points and maybe the choice of activation functions.

**Comment by stuarteiffert** [comment]
Thanks,
It trains as expected doing as you suggested.
When I was using normalised positions as inputs to V I also used the same normalised positions as inputs to anorm() without realising that the use of 1/L2 removed the need for normalised positions.
